package org.intrabet.service.auth;

import org.springframework.security.core.userdetails.UserDetails;

public interface TokenService {
    /**
     * @return Token type as string
     */
    String getTokenType();

    /**
     *
     * @return string representation of the token
     */
    String createToken(UserDetails userDetails);

    /**
     * extracts username from token
     * @param token any token generated by the same service
     * @return username in token
     */
    String getUsername(String token);

    /**
     *
     * @param token token from the save service
     * @return true in case token is not expired and username matches
     */
    boolean isTokenValid(String token, UserDetails userDetails);

    boolean isTokenExpired(String token);
}
