openapi: 3.0.0
info:
  title: Betting Application API
  description: API for a betting system including authentication, categories, events, and bets.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Local server
paths:
  /auth/register:
    post:
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationDTO'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponseDTO'
        '400':
          description: Validation error
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
  /auth/login:
    post:
      summary: Login a user
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginDTO'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponseDTO'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
  /admin/category/create:
    post:
      summary: Create a new category (admin only)
      operationId: createCategory
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDTO'
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Validation error or category exists
          content:
            text/plain:
              schema:
                type: string
  /events/create:
    post:
      summary: Create a new event
      operationId: createEvent
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatedEventDTO'
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '500':
          description: Internal server error
  /events/list:
    get:
      summary: List events
      operationId: listEvents
      parameters:
        - name: category
          in: query
          required: false
          schema:
            type: string
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Category not found
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
  /bets/place:
    post:
      summary: Place a bet
      operationId: placeBet
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BetDTO'
      responses:
        '201':
          description: Bet placed successfully
        '400':
          description: Validation error or insufficient balance
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserRegistrationDTO:
      type: object
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
      required:
        - username
        - email
        - password
    UserLoginDTO:
      type: object
      properties:
        loginOrEmail:
          type: string
        password:
          type: string
      required:
        - loginOrEmail
        - password
    AuthenticationResponseDTO:
      type: object
      properties:
        tokenType:
          type: string
        accessToken:
          type: string
      required:
        - tokenType
        - accessToken
    CategoryDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
    CreatedEventDTO:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        category:
          type: string
        startsAt:
          type: string
          format: date-time
        endsAt:
          type: string
          format: date-time
        createdOutcomes:
          type: array
          items:
            $ref: '#/components/schemas/CreatedOutcomeDTO'
          minItems: 2
      required:
        - title
        - createdOutcomes
    CreatedOutcomeDTO:
      type: object
      properties:
        description:
          type: string
      required:
        - description
    BetDTO:
      type: object
      properties:
        outcomeId:
          type: integer
          format: int64
        sum:
          type: integer
          format: int64
      required:
        - outcomeId
        - sum
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        startsAt:
          type: string
          format: date-time
        endsAt:
          type: string
          format: date-time
        status:
          type: string
          enum: [PLANNED, ONGOING, COMPLETED, CANCELLED]
        category:
          $ref: '#/components/schemas/Category'
        outcomes:
          type: array
          items:
            $ref: '#/components/schemas/Outcome'
    Outcome:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        isWinner:
          type: boolean